[package]
name = "shelves"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
rustls = "0.23.12"
thiserror = "1.0.63"
webpki = "0.22.4"
webpki-roots = "0.26.3"
